import './global.css';

import { poppinsRegular } from '@/utils/global.fonts';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`${poppinsRegular.variable}`}>
        {children}
      </body>
    </html>
  )
}
